In [1]:
import numpy as np

In [3]:
revenue = np.array ([[180, 200,220],[24,36,401], [112,18,2011]])
expenses = np.array ([[80, 90, 100], [10, 16, 20], [8,10, 10]])

In [4]:
profit = revenue - expenses
print(profit)

[[ 100  110  120]
 [  14   20  381]
 [ 104    8 2001]]


In [5]:
price_per_unit = np.array([1000,400,1200])
units  = np.array([[30,40,50],[5,10,15],[2,5,7]])

Broadcasting

In [7]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

multiplication

In [8]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])