In [92]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [93]:
digits = load_digits()

In [94]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [95]:
X = digits.data
y = digits.target

In [96]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [97]:
lr = LogisticRegression(max_iter=500)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9722222222222222

In [98]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9972222222222222

In [99]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9861111111111112

In [100]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [101]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


function for model reusability

In [102]:
def get_score(model,X_train,y_train,X_test,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

example down here

In [103]:
get_score(svm,X_train,y_train,X_test,y_test)

0.9972222222222222

In [104]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [105]:
scores_l = []
scores_svm = []
scores_rf = []

working of this. can be easily done using cross_val_score

In [106]:
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index] , digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(lr,X_train,y_train,X_test,y_test))
    scores_svm.append(get_score(svm,X_train,y_train,X_test,y_test))
    scores_rf.append(get_score(rf,X_train,y_train,X_test,y_test))

In [107]:
scores_rf

[0.9348914858096828, 0.9666110183639399, 0.9265442404006677]

In [108]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [109]:
from sklearn.model_selection import cross_val_score

In [110]:
cross_val_score(svm,digits.data,digits.target)

Parameter tuning

In [114]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93055556, 0.9       , 0.95264624, 0.95264624, 0.9275766 ])

In [115]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.875     , 0.81944444, 0.92200557, 0.90529248, 0.85236769])

In [117]:
cross_val_score(RandomForestClassifier(n_estimators=70),digits.data,digits.target)

array([0.94166667, 0.88333333, 0.94986072, 0.97493036, 0.92479109])