In [33]:
import numpy as np

In [34]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])
b=np.array([[1],[2],[3],[4]])

In [35]:
a.shape


(2, 4)

In [36]:
b.shape

(4, 1)

In [37]:

b

array([[1],
       [2],
       [3],
       [4]])

In [38]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
c=a*b

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [40]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])

In [41]:
b.shape

(4, 1)

In [42]:
a.shape

(4, 4)

In [43]:
a*b

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36],
       [52, 56, 60, 64]])

In [45]:
b=np.array([[1],[2],[3],[4],[5],[6],[7]])

In [46]:
a*b

ValueError: operands could not be broadcast together with shapes (4,4) (7,1) 

In [48]:
b.shape

(7, 1)

In [49]:
c=np.array([[1,2,3,4,5,6,7,8,9,10]])

In [52]:
d=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

In [55]:
c.shape

(1, 10)

In [56]:
d.shape

(10, 1)

In [54]:
c*d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])