In [1]:
import numpy as np

in python, the elements increases, whereas here the elements are mul by 2

In [2]:
a=np.array([1,2,3,4])
a=a*2

In [3]:
a

array([2, 4, 6, 8])

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
a.ndim

2

In [6]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],
           [[1,2,3],[4,5,6],[7,8,9]]])

In [7]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
a.ndim

3

In [9]:
a.shape


(2, 3, 3)

In [10]:
a.ndim

3

accessing elements in ndim

In [11]:
a[0][0][2]

np.int64(3)

In [12]:
a[0,0,1]

np.int64(2)

In [13]:
b=np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
           [['J','K','L'],['M','N','O'],['P','Q','R']],
           [['S','T','U'],['V','W','X'],['Y','Z',' ']]])

In [14]:
b


array([[['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']],

       [['J', 'K', 'L'],
        ['M', 'N', 'O'],
        ['P', 'Q', 'R']],

       [['S', 'T', 'U'],
        ['V', 'W', 'X'],
        ['Y', 'Z', ' ']]], dtype='<U1')

In [15]:
b.shape

(3, 3, 3)

In [16]:
b[0,1,1]

np.str_('E')

In [17]:
word=b[0,0,1]
word


np.str_('B')

concatenation


In [18]:
word=b[0,0,1]+ b[2,2,0]+ b[0,1,1]
print(word)

BYE


FILTERING:-select elements on basis of given condition

In [20]:
ages=np.array([[21,17,19,20,16,30,18,65],
              [39,22,15,99,18,19,20,21]])

In [21]:
teen=ages[ages<18]

In [22]:
teen #boolean indexing

array([17, 16, 15])

& and , | or

In [28]:
adults=ages[(ages>=18) | (ages<65)]

In [29]:
adults

array([21, 17, 19, 20, 16, 30, 18, 65, 39, 22, 15, 99, 18, 19, 20, 21])

In [30]:
even=ages[ages%2==0]
even

array([20, 16, 30, 18, 22, 18, 20])

where(condition,array,fillvalue)


In [31]:
adults=np.where(ages>=18,ages,0)

In [32]:
adults


array([[21,  0, 19, 20,  0, 30, 18, 65],
       [39, 22,  0, 99, 18, 19, 20, 21]])

In [33]:
adults.shape

(2, 8)

#note :- boolean indexing flttens data where as where preserves its original shape