In [62]:
import numpy as np

In [63]:
a=np.arange(0,100).reshape(20,5) #array created

In [64]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

index markdown error learned here


In [65]:
rows=np.random.randint(0,10,size=5)
columns=np.random.randint(0,5,size=5)

In [66]:
a[rows,columns] = -1 # add -1 randomly to add missing values

In [67]:
a

array([[ 0,  1,  2,  3, -1],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, -1, -1, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, -1, 37, 38, 39],
       [40, 41, 42, 43, -1],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [68]:
for i in range(a.shape[1]): #check every column
    curr_pos=a[:, i] #current position element temp variable
    clear_mean=curr_pos[curr_pos!=-1].mean()
    curr_pos[curr_pos ==-1]=clear_mean #mean added to missing value area

feature scaling use min-max normalization

In [69]:
a_min=a.min(axis=0)

In [70]:
a_max=a.max(axis=0)


In [71]:
a_scaled=(a-a_min)/(a_max-a_min) #min-max norm

In [72]:
a_scaled

array([[0.        , 0.        , 0.        , 0.        , 0.5       ],
       [0.05263158, 0.05263158, 0.05263158, 0.05263158, 0.        ],
       [0.10526316, 0.10526316, 0.10526316, 0.10526316, 0.05555556],
       [0.15789474, 0.15789474, 0.15789474, 0.15789474, 0.11111111],
       [0.21052632, 0.21052632, 0.50526316, 0.50526316, 0.16666667],
       [0.26315789, 0.26315789, 0.26315789, 0.26315789, 0.22222222],
       [0.31578947, 0.31578947, 0.31578947, 0.31578947, 0.27777778],
       [0.36842105, 0.50526316, 0.36842105, 0.36842105, 0.33333333],
       [0.42105263, 0.42105263, 0.42105263, 0.42105263, 0.5       ],
       [0.47368421, 0.47368421, 0.47368421, 0.47368421, 0.44444444],
       [0.52631579, 0.52631579, 0.52631579, 0.52631579, 0.5       ],
       [0.57894737, 0.57894737, 0.57894737, 0.57894737, 0.55555556],
       [0.63157895, 0.63157895, 0.63157895, 0.63157895, 0.61111111],
       [0.68421053, 0.68421053, 0.68421053, 0.68421053, 0.66666667],
       [0.73684211, 0.73684211, 0.

In [73]:
weights = np.array([0.1, 0.1, 0.2, 0.3, 0.3])

In [ ]:
a.shape

(20, 5)

In [ ]:
weights.shape

(5,)

In [74]:
weighted_matrix=a_scaled * weights

In [75]:
patient_scores = weighted_matrix.sum(axis=1)

In [76]:
highest_risk_index = patient_scores.argmax()

In [77]:
print(f"Patient at index {highest_risk_index} has the highest risk score of {patient_scores[highest_risk_index]:.2f}")

Patient at index 19 has the highest risk score of 1.00
