In [2]:
import numpy as np

In [3]:
a=np.array([5,8,3])

accessing elements in an array

In [4]:
a[0]

np.int64(5)

Multi dimensional Array

In [5]:
b=np.array([[3,45,4],[7,2,13]])

to see the dimension of the array

In [6]:
b.ndim

2

bit size
8 means 64 bytes

In [7]:
b.itemsize

8

In [8]:
a.dtype

dtype('int64')

In [9]:
a.dtype

dtype('int64')

In [10]:
a

array([5, 8, 3])

In [11]:
b

array([[ 3, 45,  4],
       [ 7,  2, 13]])

no of elements


In [12]:
a.size

3

In [13]:
b.size

6

data type changed into float


In [14]:
b=np.array([[3,45,4],[7,2,13]],dtype=float)

In [15]:
print(b.itemsize)

8


In [16]:
a.size

3

In [17]:
b

array([[ 3., 45.,  4.],
       [ 7.,  2., 13.]])

In [18]:
a

array([5, 8, 3])

In [19]:
b=np.array([[3,45,4],[7,2,13]],dtype=complex)

In [20]:
b

array([[ 3.+0.j, 45.+0.j,  4.+0.j],
       [ 7.+0.j,  2.+0.j, 13.+0.j]])

initilalise arrays with zero

In [21]:
b=np.zeros( (3,4) )

In [22]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
l=range(5)

In [25]:
l

range(0, 5)

In [26]:
l[0]

0

array created on range basis

In [27]:
np.arange(1,5)

array([1, 2, 3, 4])

In [28]:
np.arange(1,7,2)

array([1, 3, 5])

creates array with equal space between them

In [29]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [30]:
a=np.array([[1,2],[3,4],[6,5]])

dim of array


In [31]:
a.shape

(3, 2)

reshape

In [32]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 6, 5]])

flatten the array

In [33]:
a.ravel()


array([1, 2, 3, 4, 6, 5])

In [34]:
a

array([[1, 2],
       [3, 4],
       [6, 5]])

In [35]:
a.min()

np.int64(1)

In [36]:
a.max()

np.int64(6)

In [37]:
a.mean()

np.float64(3.5)

In [38]:
a.sum()

np.int64(21)

In [39]:
a.sum(axis=0)

array([10, 11])

In [40]:
a

array([[1, 2],
       [3, 4],
       [6, 5]])

In [41]:
a.sum(axis=1)

array([ 3,  7, 11])

In [42]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.44948974, 2.23606798]])

In [43]:
np.median(a)

np.float64(3.5)

In [44]:
a=np.array([[1,2],[3,4],[6,5],[2,7]])

In [45]:
a


array([[1, 2],
       [3, 4],
       [6, 5],
       [2, 7]])

In [46]:
a.ravel()

array([1, 2, 3, 4, 6, 5, 2, 7])

In [47]:
a

array([[1, 2],
       [3, 4],
       [6, 5],
       [2, 7]])

In [48]:
np.median(a)

np.float64(3.5)

In [49]:
np.std(a)

np.float64(1.984313483298443)

In [50]:
a

array([[1, 2],
       [3, 4],
       [6, 5],
       [2, 7]])

In [51]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
b=np.array([[1,5],[2,4],[3,7],[6,8]])

In [53]:
b

array([[1, 5],
       [2, 4],
       [3, 7],
       [6, 8]])

In [54]:
a+b

array([[ 2,  7],
       [ 5,  8],
       [ 9, 12],
       [ 8, 15]])

In [55]:
a.dot(b)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [56]:
a.shape

(4, 2)

In [57]:
b.shape

(4, 2)

In [58]:
a/b

array([[1.        , 0.4       ],
       [1.5       , 1.        ],
       [2.        , 0.71428571],
       [0.33333333, 0.875     ]])

scalar arithmetic


In [63]:
a=np.array([1,2,3])

In [64]:
print(a+1)

[2 3 4]


In [65]:
a-2

array([-1,  0,  1])

In [66]:
a*2

array([2, 4, 6])

vectorized math fns

In [67]:
a

array([1, 2, 3])

In [68]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [72]:
a=np.array([1.01,2.5,3.99])

In [73]:
np.sqrt(a)

array([1.00498756, 1.58113883, 1.99749844])

In [74]:
np.round(a)

array([1., 2., 4.])

In [76]:
(np.floor(a))

array([1., 2., 3.])

In [79]:
np.pi

3.141592653589793

In [81]:
np.ceil(a)

array([2., 3., 4.])

In [83]:
radii=np.array([1,2,3])

In [86]:
(np.pi*(radii)**2)

array([ 3.14159265, 12.56637061, 28.27433388])

element wise arithmetic

In [87]:
a


array([1.01, 2.5 , 3.99])

In [88]:
a=np.array([1,2,3])

In [89]:
b=np.array([4,5,6])

In [90]:
a+b

array([5, 7, 9])

In [91]:
a-b

array([-3, -3, -3])

In [92]:
a*b

array([ 4, 10, 18])

In [93]:
a/b

array([0.25, 0.4 , 0.5 ])

In [94]:
a**2

array([1, 4, 9])

comparsion op

In [95]:
scores=np.array([91,55,100,73,82,64])

In [96]:
print(scores==100)


[False False  True False False False]


In [97]:
scores>=60

array([ True, False,  True,  True,  True,  True])

In [99]:
scores[scores<60] = 0

In [100]:
scores

array([ 91,   0, 100,  73,  82,  64])