In [1]:
import numpy as np

In [2]:
a=np.array([5,8,3])

accessing elements in an array

In [3]:
a[0]

np.int64(5)

Multi dimensional Array

In [4]:
b=np.array([[3,45,4],[7,2,13]])

to see the dimension of the array

In [5]:
b.ndim

2

bit size
8 means 64 bytes

In [6]:
b.itemsize

8

In [7]:
a.dtype

dtype('int64')

In [8]:
a.dtype

dtype('int64')

In [9]:
a

array([5, 8, 3])

In [10]:
b

array([[ 3, 45,  4],
       [ 7,  2, 13]])

no of elements


In [11]:
a.size

3

In [12]:
b.size

6

data type changed into float


In [12]:
b=np.array([[3,45,4],[7,2,13]],dtype=float)

In [13]:
print(b.itemsize)

8


In [15]:
a.size

3

In [16]:
b

array([[ 3, 45,  4],
       [ 7,  2, 13]])

In [17]:
a

array([5, 8, 3])

In [20]:
b=np.array([[3,45,4],[7,2,13]],dtype=complex)

In [21]:
b

array([[ 3.+0.j, 45.+0.j,  4.+0.j],
       [ 7.+0.j,  2.+0.j, 13.+0.j]])

initilalise arrays with zero

In [26]:
b=np.zeros( (3,4) )

In [27]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
l=range(5)

In [30]:
l

range(0, 5)

In [31]:
l[0]

0

array created on range basis

In [34]:
np.arange(1,5)

array([1, 2, 3, 4])

In [35]:
np.arange(1,7,2)

array([1, 3, 5])

creates array with equal space between them

In [36]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [37]:
a=np.array([[1,2],[3,4],[6,5]])

dim of array


In [42]:
a.shape

(3, 2)

reshape

In [44]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 6, 5]])

flatten the array

In [45]:
a.ravel()


array([1, 2, 3, 4, 6, 5])

In [46]:
a

array([[1, 2],
       [3, 4],
       [6, 5]])

In [47]:
a.min()

np.int64(1)

In [49]:
a.max()

np.int64(6)

In [50]:
a.mean()

np.float64(3.5)

In [52]:
a.sum()

np.int64(21)

In [53]:
a.sum(axis=0)

array([10, 11])

In [54]:
a

array([[1, 2],
       [3, 4],
       [6, 5]])

In [55]:
a.sum(axis=1)

array([ 3,  7, 11])

In [56]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.44948974, 2.23606798]])

In [57]:
np.median(a)

np.float64(3.5)

In [60]:
a=np.array([[1,2],[3,4],[6,5],[2,7]])

In [61]:
a


array([[1, 2],
       [3, 4],
       [6, 5],
       [2, 7]])

In [62]:
a.ravel()

array([1, 2, 3, 4, 6, 5, 2, 7])

In [63]:
a

array([[1, 2],
       [3, 4],
       [6, 5],
       [2, 7]])

In [64]:
np.median(a)

np.float64(3.5)

In [66]:
np.std(a)

np.float64(1.984313483298443)

In [67]:
a

array([[1, 2],
       [3, 4],
       [6, 5],
       [2, 7]])

In [68]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
b=np.array([[1,5],[2,4],[3,7],[6,8]])

In [70]:
b

array([[1, 5],
       [2, 4],
       [3, 7],
       [6, 8]])

In [71]:
a+b

array([[ 2,  7],
       [ 5,  8],
       [ 9, 12],
       [ 8, 15]])

In [72]:
a.dot(b)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [73]:
a.shape

(4, 2)

In [74]:
b.shape

(4, 2)