In [14]:
import numpy as np

In [15]:
rng = np.random.default_rng()

In [16]:
rng.integers(1,7)

np.int64(5)

In [17]:
rng.integers(low=1,high=101)

np.int64(8)

count is given in size

In [18]:
rng.integers(low=1,high=101,size=10)

array([57,  9, 32,  6, 49, 85, 50, 10, 39, 91])

dimension

In [19]:
rng.integers(low=1,high=101,size=(3,2))

array([[52, 92],
       [81, 55],
       [32, 12]])

seed used to reproduce same results

In [28]:
rng = np.random.default_rng(seed=1)

In [34]:
rng.integers(low=1,high=101,size=(3,2))

array([[13, 46],
       [98, 14],
       [39, 41]])

floating point num


In [35]:
rn=np.random.uniform()

In [36]:
rn

0.8027396661682495

range

In [37]:
rn=np.random.uniform(-1,1)

In [38]:
rn

-0.388664620823546

In [45]:
rn=np.random.seed()

In [48]:
rn=np.random.uniform(-1,1,size=(3,2))
rn

array([[ 0.99676293,  0.07188405],
       [-0.93781148,  0.60339002],
       [-0.52808275,  0.04760687]])

In [49]:
a=np.array([1,2,3,4,5])

In [50]:
a

array([1, 2, 3, 4, 5])

shuffle

In [51]:
rng=np.random.default_rng()

In [53]:
rng.shuffle(a)

None


In [54]:
a


array([4, 3, 5, 2, 1])

In [56]:
a

array([4, 3, 5, 2, 1])

In [57]:
fruits=(['apple','orange','kiwi','butter'])

In [58]:
rng.shuffle(fruits)

In [59]:
fruits

['orange', 'kiwi', 'butter', 'apple']

In [61]:
fruit=rng.choice(fruits)

In [62]:
fruit

np.str_('apple')

In [68]:
fruit=rng.choice(fruits,size=(3))

In [69]:
fruit

array(['orange', 'orange', 'kiwi'], dtype='<U6')

In [70]:
fruit=rng.choice(fruits,size=(3,2))

In [71]:
fruitss=np.array(["🍒","🍓","🍌","🥝"])

In [72]:
fruitss

array(['🍒', '🍓', '🍌', '🥝'], dtype='<U1')

In [73]:
rng.choice(fruitss)

np.str_('🍌')