In [4]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

a[start:end:step]

In [7]:
a[-2]

array([ 9, 10, 11, 12])

In [8]:
a[3]

array([13, 14, 15, 16])

In [9]:
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
a[0:3+1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
a[0:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
a[0:4:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [13]:
a[::-2]

array([[13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [14]:
a[::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
a[0,0]

np.int64(1)

accessing all element in index position 0
colon for entire column selection


In [16]:
b=a[:,0]

In [17]:
b


array([ 1,  5,  9, 13])

a[:,0] for ':; for rows position and value for column

In [18]:
a[:,2]

array([ 3,  7, 11, 15])

In [19]:
a[:,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [21]:
a[:,::-2]

array([[ 4,  2],
       [ 8,  6],
       [12, 10],
       [16, 14]])

a[0,:] positional argument like x,y select row not column

In [22]:
a[0,:]

array([1, 2, 3, 4])

In [24]:
a[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

row and column using indexing


In [26]:
a[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [27]:
a[3,3]

np.int64(16)

In [28]:
a[3:,3:]

array([[16]])

In [29]:
a[2:,2:]

array([[11, 12],
       [15, 16]])

In [31]:
a[2:4,2:]

array([[11, 12],
       [15, 16]])